/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import javax.swing.*;
import negocio.UsuarioNegocio;
import java.awt.GridLayout;

public class CrearCuentaForm extends javax.swing.JFrame {
    private JTextField txtUsuario;
    private JPasswordField txtPassword;
    private JButton btnCrear;
    
    public CrearCuentaForm() {
        setTitle("Crear cuenta");
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(3, 2));

        panel.add(new JLabel("Nuevo Usuario:"));
        txtUsuario = new JTextField();
        panel.add(txtUsuario);

        panel.add(new JLabel("Contraseña:"));
        txtPassword = new JPasswordField();
        panel.add(txtPassword);

        btnCrear = new JButton("Crear cuenta");
        panel.add(btnCrear);

        add(panel);

        btnCrear.addActionListener(e -> {
            String usuario = txtUsuario.getText();
            String contrasena = new String(txtPassword.getPassword());
            // Lógica para crear el usuario en la base de datos
            UsuarioNegocio.crearUsuario(usuario, contrasena);
            JOptionPane.showMessageDialog(this, "Cuenta creada exitosamente.");
            LoginForm loginForm = new LoginForm();
            loginForm.setVisible(true);
            this.dispose();  // Cerrar la ventana de crear cuenta
        });
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            CrearCuentaForm form = new CrearCuentaForm();
            form.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
