/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package presentacion;

import javax.swing.*;

public class ModuloSeleccionForm extends javax.swing.JFrame {
    private JButton btnContabilidad;
    private JButton btnNomina;
    private JButton btnSeleccion;
    private JButton btnBiblioteca;
    
    public ModuloSeleccionForm() {
        setTitle("Seleccionar Módulo");
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        JPanel panel = new JPanel();
        panel.setLayout(new GridLayout(5, 1));

        btnContabilidad = new JButton("Contabilidad");
        btnNomina = new JButton("Nómina");
        btnSeleccion = new JButton("Selección");
        btnBiblioteca = new JButton("Biblioteca");

        panel.add(btnContabilidad);
        panel.add(btnNomina);
        panel.add(btnSeleccion);
        panel.add(btnBiblioteca);

        add(panel);

        btnBiblioteca.addActionListener(e -> {
            // Redirigir al formulario de biblioteca
            BibliotecaForm bibliotecaForm = new BibliotecaForm();
            bibliotecaForm.setVisible(true);
            this.dispose();  // Cerrar el modulo de selección
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> {
            ModuloSeleccionForm form = new ModuloSeleccionForm();
            form.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
